"""empty message

Revision ID: 4075ee608ebb
Revises: a6dc7259041b
Create Date: 2022-08-21 17:18:10.945015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4075ee608ebb'
down_revision = 'a6dc7259041b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'favorites_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favorites_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'favorites', ['favorites_id'], ['id'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'user_id')
    # ### end Alembic commands ###
